# Generated by Django 5.2.8 on 2025-11-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('practice', 'Practice (Untimed)'), ('quiz', 'Quiz (Timed)')], default='practice', max_length=20)),
                ('difficulty', models.CharField(blank=True, max_length=10, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'practice_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('msq', 'Multiple Select'), ('numerical', 'Numerical'), ('subjective', 'Subjective')], default='mcq', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=100)),
                ('solution', models.TextField(blank=True, null=True)),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='solutions/')),
                ('marks', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['subject', 'topic', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('test_type', models.CharField(choices=[('chapter', 'Chapter-wise Test'), ('subject', 'Subject Test'), ('full', 'Full Syllabus Test'), ('mock', 'Mock Test'), ('daily', 'Daily Practice Test')], default='chapter', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_proctored', models.BooleanField(default=False)),
                ('show_answers_after', models.BooleanField(default=True)),
                ('allow_review', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tests',
                'ordering': ['-start_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('unattempted_count', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'test_responses',
            },
        ),
    ]
