# Generated by Django 5.2.8 on 2025-11-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_linked_students_remove_user_referred_by_and_more'),
        ('batches', '0003_language_alter_batch_options_remove_batch_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subjects',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='faculty_members', to='batches.subject'),
        ),
    ]
