# Generated by Django 5.2.3 on 2025-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Batches'},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='batch',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='batch',
            name='includes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='batch',
            name='promo_video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='target_class',
            field=models.CharField(choices=[('class_6', 'Class 6'), ('class_7', 'Class 7'), ('class_8', 'Class 8'), ('class_9', 'Class 9'), ('class_10', 'Class 10'), ('class_11', 'Class 11'), ('class_12', 'Class 12'), ('foundation', 'Foundation'), ('drop_year', 'Drop Year')], max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='target_year',
            field=models.IntegerField(blank=True, choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='batch_thumbnails/'),
        ),
    ]
