# Generated by Django 5.2.8 on 2025-11-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_language_alter_batch_options_remove_batch_faculty_and_more'),
        ('users', '0003_remove_faculty_subjects_faculty_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='batches', to='users.faculty'),
        ),
        migrations.CreateModel(
            name='BatchSubjectFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_subject_faculties', to='batches.batch')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.subject')),
            ],
            options={
                'db_table': 'batch_subject_faculties',
                'unique_together': {('batch', 'subject', 'faculty')},
            },
        ),
    ]
