# Generated by Django 5.2.8 on 2025-11-25 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('content', '0002_initial'),
        ('doubts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doubts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doubt',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts', to='content.lecture'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doubt',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='batches.subject'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts', to='batches.topic'),
        ),
        migrations.AddField(
            model_name='doubtresponse',
            name='doubt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='doubts.doubt'),
        ),
        migrations.AddField(
            model_name='doubtresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doubtupvote',
            name='doubt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvote_records', to='doubts.doubt'),
        ),
        migrations.AddField(
            model_name='doubtupvote',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvote_records', to='doubts.doubtresponse'),
        ),
        migrations.AddField(
            model_name='doubtupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='doubtupvote',
            unique_together={('user', 'doubt'), ('user', 'response')},
        ),
    ]
